# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"
  db_test:
    container_name: "db_test"
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${TEST_POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${TEST_POSTGRES_DB?Variable not set}
    ports:
      - "5433:5432"
