
services:

# Monitoring
####################################
  prometheus:
    networks:
      - fastapi-prom
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./backend/compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  grafana:
    networks:
      - fastapi-prom
    image: grafana/grafana
    container_name: my_grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

#########################################
volumes:

  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data


networks:
  fastapi-prom:
    external: true
