"""add relate reports

Revision ID: 883cecddd829
Revises: 9c7eb53a7abd
Create Date: 2024-05-21 00:18:39.877250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = '883cecddd829'
down_revision: Union[str, None] = '9c7eb53a7abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OzonReport',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report', sa.LargeBinary(), nullable=False),
    sa.Column('ozon_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OzonReport_id'), 'OzonReport', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OzonReport_id'), table_name='OzonReport')
    op.drop_table('OzonReport')
    # ### end Alembic commands ###
