"""add hash-password column in table users

Revision ID: 69e034411b09
Revises: c56372749340
Create Date: 2024-04-25 15:50:09.234088

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "69e034411b09"
down_revision = "c56372749340"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
