"""empty message

Revision ID: c0bc38842904
Revises: ad4df92b4089
Create Date: 2024-06-13 13:19:27.686792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'c0bc38842904'
down_revision: Union[str, None] = 'ad4df92b4089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_User_role_id', 'User', type_='unique')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_User_role_id', 'User', ['role_id'])
    # ### end Alembic commands ###
