"""add relate users

Revision ID: f0fe2ce98f9c
Revises: 0fa68411d496
Create Date: 2024-05-11 14:18:38.845961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0fe2ce98f9c'
down_revision: Union[str, None] = '0fa68411d496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_OzonData_id', table_name='OzonData')
    op.drop_table('OzonData')
    op.drop_column('User', 'role')
    op.drop_column('User', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_table('OzonData',
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='OzonData_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='OzonData_pkey'),
    sa.UniqueConstraint('user_id', name='OzonData_user_id_key')
    )
    op.create_index('ix_OzonData_id', 'OzonData', ['id'], unique=False)
    # ### end Alembic commands ###
