"""add relationship many-to-many for User and OzonReport

Revision ID: 602870d72ff1
Revises: dc5edc2bfc38
Create Date: 2024-05-22 15:49:27.511818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = '602870d72ff1'
down_revision: Union[str, None] = 'dc5edc2bfc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinkUserOzonReport',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ozon_report_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['ozon_report_id'], ['OzonReport.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'ozon_report_id')
    )
    op.create_index(op.f('ix_LinkUserOzonReport_id'), 'LinkUserOzonReport', ['id'], unique=False)
    op.drop_constraint('OzonReport_user_id_fkey', 'OzonReport', type_='foreignkey')
    op.drop_column('OzonReport', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OzonReport', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('OzonReport_user_id_fkey', 'OzonReport', 'User', ['user_id'], ['id'])
    op.drop_index(op.f('ix_LinkUserOzonReport_id'), table_name='LinkUserOzonReport')
    op.drop_table('LinkUserOzonReport')
    # ### end Alembic commands ###
