"""empty message

Revision ID: ad4df92b4089
Revises: 7ee9cf914566
Create Date: 2024-06-13 12:13:26.370695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'ad4df92b4089'
down_revision: Union[str, None] = '7ee9cf914566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint("uq_User_role_id", 'User', ['role_id'])
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_User_role_id", 'User', type_='unique')
    op.alter_column('User', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
