"""add relate role

Revision ID: c3caf25c3782
Revises: f0fe2ce98f9c
Create Date: 2024-05-11 14:20:39.513714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = 'c3caf25c3782'
down_revision: Union[str, None] = 'f0fe2ce98f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Role_id'), 'Role', ['id'], unique=False)
    op.add_column('User', sa.Column('role_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key("User_role_id_fkey", 'User', 'Role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("User_role_id_fkey", 'User', type_='foreignkey')
    op.drop_column('User', 'role_id')
    op.drop_index(op.f('ix_Role_id'), table_name='Role')
    op.drop_table('Role')
    # ### end Alembic commands ###
